sudo: required

language: minimal

services:
  - docker

env:
  - CLAIR_VERSION=v2.0.7 CLAIR_LOCAL_SCAN_IMAGE=arminc/clair-local-scan

install:
  - docker build -t $CLAIR_LOCAL_SCAN_IMAGE --build-arg VERSION=$CLAIR_VERSION clair

before_script:
  - docker run -d --name postgres -e 'PGDATA=/var/lib/postgresql/clair' -e POSTGRES_PASSWORD=password arminc/clair-db:$(date --date="-1 day" +%Y-%m-%d)
  - until docker run --rm -it --link postgres:postgres -e PGPASSWORD=password postgres:11.1-alpine pg_isready -U postgres -h postgres; do sleep 1; done
  - docker run -d --name clair --link postgres:postgres $CLAIR_LOCAL_SCAN_IMAGE

script:
  - ./check.sh

after_success:
  - docker stop clair
  - docker stop postgres
  - docker commit postgres arminc/clair-db:$(date +%Y-%m-%d)
  - docker tag arminc/clair-db:$(date +%Y-%m-%d) arminc/clair-db:latest
  - docker tag $CLAIR_LOCAL_SCAN_IMAGE ${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${TRAVIS_COMMIT}
  - docker images

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  on:
    branch: master
  script:
    docker push ${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${TRAVIS_COMMIT} &&
    docker push $CLAIR_LOCAL_SCAN_IMAGE:latest && 
    docker push arminc/clair-db:$(date +%Y-%m-%d) &&
    docker push arminc/clair-db:latest